# .travis.yml
language: node_js

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

node_js:
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'

env:
  - POSTGRESQL_VERSION=9.4 MYSQL_VERSION=5.5
  - POSTGRESQL_VERSION=9.5 MYSQL_VERSION=5.6
  - POSTGRESQL_VERSION=9.6 MYSQL_VERSION=5.7
  - POSTGRESQL_VERSION=10 MYSQL_VERSION=8 PGPORT=5433

before_install:
  - sudo service postgresql stop
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql start $POSTGRESQL_VERSION
  - sudo service mysql stop || sudo service mysql-5.6 stop || sudo stop mysql-5.6 || sudo stop mysql || echo "failed to stop mysql"
  - sudo docker pull mysql:$MYSQL_VERSION
  - sudo docker run --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -d mysql:$MYSQL_VERSION
  - sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=eioC9vvCZzQSy4S9g37i' -p 1433:1433 -d microsoft/mssql-server-linux:2017-CU8
  - sleep 20

before_script:
  - psql -U postgres -c "CREATE USER db_errors SUPERUSER"
  - psql -U postgres -c "CREATE DATABASE db_errors_test"
  - if [ $MYSQL_VERSION == "8" ]; then docker exec mysql mysql --user=root --password=root -h 127.0.0.1 --protocol=tcp -e "CREATE USER db_errors IDENTIFIED WITH mysql_native_password"; else docker exec mysql mysql --user=root --password=root -h 127.0.0.1 --protocol=tcp -e "CREATE USER db_errors"; fi
  - docker exec mysql mysql --user=root --password=root -h 127.0.0.1 --protocol=tcp -e "GRANT ALL PRIVILEGES ON *.* TO db_errors"
  - docker exec mysql mysql --user=root --password=root -h 127.0.0.1 --protocol=tcp -e "CREATE DATABASE db_errors_test"

script:
  - npm run-script test-travis

notifications:
  email: false
